Repository polyfy/polylith, pull requests merged in 2020-11, with the labels that each got.

#54 Updated documentation
  images/base.png
  images/component-interface.png
  images/component.png
  images/development.png
  images/project.png
  readme.md
Labels: documentation

#55 Alpha5 Release
  components/version/src/polylith/clj/core/version/interface.clj
  doc/commands.md
  readme.md
Labels: release

#56 Installation Instructions
  components/creator/src/polylith/clj/core/creator/workspace.clj
  components/creator/test/polylith/clj/core/creator/workspace_test.clj
  example/sections/workspace/deps.edn
  readme.md
Labels: documentation

#57 Updated doc
  components/creator/src/polylith/clj/core/creator/workspace.clj
  components/creator/test/polylith/clj/core/creator/workspace_test.clj
  components/validator/test/polylith/clj/core/validator/dev_config_test.clj
  components/workspace/test/polylith/clj/core/workspace/text_table/ws_table_test.clj
  example/sections/base/deps.edn
  example/sections/component/deps.edn
  example/sections/profile/deps.edn
  example/sections/project/deps.edn
  example/sections/testing/deps.edn
  example/sections/workspace/deps.edn
  images/add-files-to-git-dialog.png
  images/component-dirs.png
  images/doc.png
  images/logo.png
  images/repl-edit-configuration.png
  images/test-in-repl-failing.png
  images/test-in-repl-success.png
  readme.md
Labels: bug, documentation

#58 Version 0.1.0-alpha6 release
  components/version/src/polylith/clj/core/version/interface.clj
  doc/commands.md
  readme.md
Labels: release

#59 Clarified the instructions for how to switch profiles in the REPL.
  readme.md
Labels: documentation
