Repository polyfy/polylith, pull requests merged in 2020-10, with the labels that each got.

#28 Handle :user-input correctly
  components/command/src/polylith/clj/core/command/core.clj
  components/command/src/polylith/clj/core/command/interface.clj
  components/help/src/polylith/clj/core/help/libs.clj
  components/help/src/polylith/clj/core/help/summary.clj
  components/help/src/polylith/clj/core/help/ws.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/core.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/interface.clj
  components/workspace/src/polylith/clj/core/workspace/core.clj
  development/src/dev/jocke.clj
  readme.md
Labels: bug

#29 Various changes
  components/command/src/polylith/clj/core/command/core.clj
  components/command/src/polylith/clj/core/command/test.clj
  components/creator/src/polylith/clj/core/creator/workspace.clj
  components/creator/test/polylith/clj/core/creator/workspace_test.clj
  components/deps/src/polylith/clj/core/deps/text_table/lib_table.clj
  components/deps/test/polylith/clj/core/deps/text_table/lib_table_test.clj
  components/path-finder/src/polylith/clj/core/path_finder/interface/extract.clj
  components/path-finder/src/polylith/clj/core/path_finder/lib_dep_extractor.clj
  components/path-finder/src/polylith/clj/core/path_finder/path_extractor.clj
  components/path-finder/src/polylith/clj/core/path_finder/profile_src_splitter.clj
  components/path-finder/test/polylith/clj/core/path_finder/extract_path_entries_test.clj
  components/path-finder/test/polylith/clj/core/path_finder/lib_dep_extractor_test.clj
  components/path-finder/test/polylith/clj/core/path_finder/splitter_test.clj
  components/test-runner/src/polylith/clj/core/test_runner/core.clj
  components/test-runner/src/polylith/clj/core/test_runner/interface.clj
  components/user-config/src/polylith/clj/core/user_config/core.clj
  components/user-config/src/polylith/clj/core/user_config/interface.clj
  components/user-input/src/polylith/clj/core/user_input/core.clj
  components/user-input/test/polylith/clj/core/user_input/interface_test.clj
  components/validator/src/polylith/clj/core/validator/interface.clj
  components/validator/src/polylith/clj/core/validator/m107_missing_componens_in_environment.clj
  components/validator/src/polylith/clj/core/validator/user_input/profile_validator.clj
  components/validator/src/polylith/clj/core/validator/user_input/validator.clj
  components/validator/test/polylith/clj/core/validator/m107_missing_componens_in_environment_test.clj
  components/validator/test/polylith/clj/core/validator/user_input/profile_validator_test.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/core.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/library.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/profile.clj
  components/workspace/src/polylith/clj/core/workspace/core.clj
  components/workspace/src/polylith/clj/core/workspace/environment.clj
  components/workspace/src/polylith/clj/core/workspace/text_table/info_tables.clj
  components/workspace/src/polylith/clj/core/workspace/text_table/profile.clj
  components/workspace/src/polylith/clj/core/workspace/text_table/ws_table.clj
  components/workspace/src/polylith/clj/core/workspace/user_input.clj
  components/workspace/test/polylith/clj/core/workspace/environment_test.clj
  components/workspace/test/polylith/clj/core/workspace/text_table/ws_table_test.clj
  deps.edn
  images/realworld-lib-deps-compact.png
  images/realworld-lib-deps.png
  images/test-run.png
  readme.md
Labels: bug

#34 Updated the poly-git-sha
  components/common/src/polylith/clj/core/common/interface.clj
  components/creator/src/polylith/clj/core/creator/workspace.clj
  components/creator/test/polylith/clj/core/creator/workspace_test.clj
  components/migrator/src/polylith/clj/core/migrator/core.clj
  components/version/src/polylith/clj/core/version/interface.clj
  environments/migrator/deps.edn
  example/create-example.sh
  example/output/git-log-pretty.txt
  example/output/git-log.txt
  example/output/profile-ws.txt
  example/output/tagging-log-release.txt
  example/output/tagging-log.txt
  example/output/testing-test-all.txt
  example/output/testing-test-ok.txt
  images/color-info.png
  images/color-none.png
  images/flags-included.png
  images/polylith-info-bright.png
  images/polylith-info.png
  readme.md
Labels: core, documentation

#35 Updated poly-git-sha to be419d4
  components/version/src/polylith/clj/core/version/interface.clj
Labels: core

#36 Create GitHub release through CI
  .circleci/config.yml
  .gitignore
  .idea/vcs.xml
  bases/deployer-cli/src/polylith/clj/core/deployer_cli/core.clj
  components/deployer/src/polylith/clj/core/deployer/core.clj
  components/deployer/src/polylith/clj/core/deployer/interface.clj
  components/validator/test/polylith/clj/core/validator/m107_missing_componens_in_environment_test.clj
  components/version/src/polylith/clj/core/version/interface.clj
  deps.edn
  development/src/dev/jocke.clj
  environments/api/partial_pom.xml
  environments/poly-migrator/deps.edn
  environments/poly-migrator/partial_pom.xml
  environments/poly/partial_pom.xml
  scripts/build-migrator-uberjar.sh
  scripts/build-poly-migrator-uberjar.sh
Labels: core

#40 0.1.0-alpha3 release
  components/creator/src/polylith/clj/core/creator/workspace.clj
  components/creator/test/polylith/clj/core/creator/workspace_test.clj
  components/migrator/src/polylith/clj/core/migrator/core.clj
  components/version/src/polylith/clj/core/version/interface.clj
Labels: core

#41 Validation bug
  components/command/src/polylith/clj/core/command/cmd_validator/core.clj
  components/command/src/polylith/clj/core/command/cmd_validator/create.clj
  components/command/src/polylith/clj/core/command/cmd_validator/executable.clj
  components/command/src/polylith/clj/core/command/core.clj
  components/command/src/polylith/clj/core/command/create.clj
  components/command/test/polylith/clj/core/command/cmd_validator/core_test.clj
  components/command/test/polylith/clj/core/command/cmd_validator/executable_outside_ws_test.clj
  projects/poly/deps.edn
Labels: bug

#42 Added the 'version' command.
  components/command/src/polylith/clj/core/command/cmd_validator/executable.clj
  components/command/src/polylith/clj/core/command/core.clj
  components/command/test/polylith/clj/core/command/cmd_validator/executable_outside_ws_test.clj
  components/help/src/polylith/clj/core/help/create_base.clj
  components/help/src/polylith/clj/core/help/create_component.clj
  components/help/src/polylith/clj/core/help/create_project.clj
  components/help/src/polylith/clj/core/help/create_workspace.clj
  components/help/src/polylith/clj/core/help/summary.clj
  components/migrator/src/polylith/clj/core/migrator/core.clj
  components/validator/src/polylith/clj/core/validator/data.clj
  components/workspace-clj/src/polylith/clj/core/workspace_clj/core.clj
  deps.edn
  example/sections/workspace/deps.edn
  readme.md
Labels: core, documentation

#43 Release 0.1.0 alpha4
  .circleci/config.yml
  components/version/src/polylith/clj/core/version/interface.clj
  readme.md
Labels: release

#45 Moved the 'commands' section to the wiki.
  components/help/src/polylith/clj/core/help/summary.clj
  readme.md
Labels: documentation

#46 Updated to correct links to wiki from readme.
  readme.md
Labels: documentation

#48 Update doc based on corrections from James and Rachel
  bases/deployer-cli/src/polylith/clj/core/deployer_cli/core.clj
  components/deployer/src/polylith/clj/core/deployer/core.clj
  components/help/src/polylith/clj/core/help/check.clj
  components/help/src/polylith/clj/core/help/deps.clj
  components/help/src/polylith/clj/core/help/deps_project.clj
  components/help/src/polylith/clj/core/help/info.clj
  components/help/src/polylith/clj/core/help/ws.clj
  components/user-config/src/polylith/clj/core/user_config/core.clj
  components/validator/src/polylith/clj/core/validator/m108_project_with_multi_implementing_component.clj
  components/validator/test/polylith/clj/core/validator/m108_project_with_multi_implementing_component_test.clj
  doc/ci-and-deployment.md
  doc/commands.md
  readme.md
Labels: documentation

#50 Update doc 15
  components/git/test/polylith/clj/core/git/interface_test.clj
  doc/ci-and-deployment.md
  readme.md
Labels: documentation

#51 Updated links.
  doc/ci-and-deployment.md
Labels: documentation

#52 Updated links (second try).
  doc/ci-and-deployment.md
Labels: documentation
