Repository polyfy/polylith, pull requests merged in 2021-12, with the labels that each got.

#169 Update libraries to the latest version.
  components/deps/deps.edn
  components/file/deps.edn
  components/migrator/deps.edn
  components/tap/deps.edn
  components/validator/deps.edn
  components/version/src/polylith/clj/core/version/interface.clj
  components/workspace-clj/deps.edn
  components/ws-explorer/deps.edn
  deps.edn
  projects/poly/test/project/poly/workspace_test.clj
  scripts/output/polylith1/deps-migrated.txt
  scripts/output/polylith1/deps.txt
  scripts/output/polylith1/info-migrated.txt
  scripts/output/polylith1/info.txt
  scripts/output/polylith1/libs-migrated.txt
  scripts/output/polylith1/libs.txt
  scripts/output/project-tree.txt
  scripts/output/workspace-tree.txt
Labels: improvement

#172 Use .m2 root if configured in ~/.polylith/config.edn
  components/deps/src/polylith/clj/core/deps/interface.clj
  components/deps/src/polylith/clj/core/deps/lib_deps.clj
  components/test-runner/src/polylith/clj/core/test_runner/core.clj
  components/version/src/polylith/clj/core/version/interface.clj
  scripts/output/polylith1/libs-migrated.txt
  scripts/output/polylith1/libs.txt
  scripts/output/project-tree.txt
  scripts/output/workspace-tree.txt
Labels: improvement

#170 Updated CI & Deployment documentation
  doc/ci-and-deployment.md
Labels: documentation

#173 Use correct path to maven repository when running tests
  components/deps/src/polylith/clj/core/deps/lib_deps.clj
  components/user-config/src/polylith/clj/core/user_config/core.clj
  components/user-config/src/polylith/clj/core/user_config/interface.clj
  projects/poly/test/project/poly/workspace_test.clj
Labels: bug
